export const questions = [
    '',
    '',
    '',
    '',
    'If given the opportunity to be the boss for a day, which is the first thing you would do?',
    'If you had to meet any historical figure and choose him as your teammate, who would it be?',
    'What was your dream job when you were a kid?',
    'What is the most memorable thing you bought with your first salary?',
    'Altogether, what is your favorite thing about your team?',
    'According to you, what is the most mind-numbingly dull movie ever made?',
    'What is the most underrated song that everyone should listen to at least once in their life?',
    'All in all, the movie that had the most significant impact on your life and why?',
    'If you could switch your life with any fictional character, who would it be?',
    'According to you, what is the most monotonous sport to watch?Why?',
    'You now have the option of only viewing a particular celebrity\'s work for the rest of your life. Who do you choose?',
    'If you had the chance to be in the Olympics, which sport would you compete in?',
    'Generally, which reel life character are you most inspired by?',
    'Given the chance to star in any movie, what will be the movie most likely be about?',
    'Which song can cheer you up? Can you please Sing it?',
    'Do you follow any family tradition that centers around movies, sports, or songs?',
    'You have the chance to work with any celebrity that you want. Who would you choose?',
    'What is your "I wish I had started doing this earlier in my life"?',
    'Tell us the best piece of advice you\'ve ever received in your life?',
    'If you had the chance to go back and start again, what age would you choose?',
    'If you could meet any historical figure and ask them only one question?',
    'Who is the most inspirational person that you\'ve ever met?',
    'What was your fondest memory from high school?'
]